pipx install Flask --include-deps
pipx install Django --include-deps
pipx install requests --include-deps
pipx install numpy --include-deps
pipx install pandas --include-deps
pipx install matplotlib --include-deps
pipx install scipy --include-deps
pipx install scikit-learn --include-deps
pipx install tensorflow --include-deps
pipx install keras --include-deps
pipx install torch --include-deps
pipx install beautifulsoup4 --include-deps
pipx install Pillow --include-deps
pipx install SQLAlchemy --include-deps
pipx install pygame --include-deps